- name: Install a .deb package from the internet.
  apt:
    deb: https://dl.grafana.com/oss/release/grafana_6.0.2_amd64.deb

- name: Make sure grafana is running and starts at boot
  systemd: name=grafana-server state=started enabled=yes

- name: create dashboards directory
  file:
    path: /var/lib/grafana/dashboards
    state: directory

- name: Copy dashboard json
  copy: src={{ item.src }} dest={{ item.dest }}
  with_items:
    - { src: 'test.json', dest: '/var/lib/grafana/dashboards' }

- name: Create prometheus datasource
  grafana_datasource:
    name: "prometheus"
    grafana_url: "http://localhost:3000"
    grafana_user: "admin"
    grafana_password: "admin"
    org_id: "1"
    ds_type: "prometheus"
    url: "http://localhost:9090"
    database: "#{$database_name}"
    time_interval: "5s"

- name: Import Grafana dashboard foo
  grafana_dashboard:
    grafana_url: http://localhost:3000
    grafana_user: "admin"
    grafana_password: "admin"
    state: present
    message: Updated by ansible
    overwrite: yes
    path: /var/lib/grafana/dashboards/test.json

